services:
  db:
    container_name: "chickenDirect"
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=chickenDirect
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=pirate