spring:
  application:
    name: chickenDirect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: appuser
    password: pirate
    url: jdbc:postgresql://localhost:5432/chickenDirect
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - env
        - beans
        - prometheus
  server:
    port: 8090